const menu=[
    {category: "Jugo/Batido",
    imageUrl: "https://recetasdebatidos.com/wp-content/uploads/2021/02/batidos-de-frutas-naturales.jpg",
    name: "Jugo de durazno",
    price: "8", 
    description: "-"},
    {category: "Jugo/Batido",
    imageUrl: "https://recetasdebatidos.com/wp-content/uploads/2021/02/batidos-de-frutas-naturales.jpg",
    name: "Batido de durazno",
    price: "9", 
    description: "-"},
    {category: "Jugo/Batido",
    imageUrl: "https://recetasdebatidos.com/wp-content/uploads/2021/02/batidos-de-frutas-naturales.jpg",
    name: "Jugo de frutilla",
    price: "8", 
    description: "-"},
    {category: "Jugo/Batido",
    imageUrl: "https://recetasdebatidos.com/wp-content/uploads/2021/02/batidos-de-frutas-naturales.jpg",
    name: "Batido de frutilla",
    price: "9", 
    description: "-"},
    {category: "Jugo/Batido",
    imageUrl: "https://recetasdebatidos.com/wp-content/uploads/2021/02/batidos-de-frutas-naturales.jpg",
    name: "Jugo de mora",
    price: "8", 
    description: "-"},
    {category: "Jugo/Batido",
    imageUrl: "https://recetasdebatidos.com/wp-content/uploads/2021/02/batidos-de-frutas-naturales.jpg",
    name: "Batido de mora",
    price: "9", 
    description: "-"},
    {category: "Jugo/Batido",
    imageUrl: "https://recetasdebatidos.com/wp-content/uploads/2021/02/batidos-de-frutas-naturales.jpg",
    name: "Batido de platano con oreo",
    price: "8,50", 
    description: "-"},
    {category: "Jugo/Batido",
    imageUrl: "https://recetasdebatidos.com/wp-content/uploads/2021/02/batidos-de-frutas-naturales.jpg",
    name: "Jugo de piña",
    price: "8", 
    description: "-"},
    {category: "Jugo/Batido",
    imageUrl: "https://recetasdebatidos.com/wp-content/uploads/2021/02/batidos-de-frutas-naturales.jpg",
    name: "Batido de piña",
    price: "9", 
    description: "-"},
    {category: "Jugo/Batido",
    imageUrl: "https://recetasdebatidos.com/wp-content/uploads/2021/02/batidos-de-frutas-naturales.jpg",
    name: "Jugo de papaya",
    price: "8", 
    description: "-"},
    {category: "Jugo/Batido",
    imageUrl: "https://recetasdebatidos.com/wp-content/uploads/2021/02/batidos-de-frutas-naturales.jpg",
    name: "Batido de papaya",
    price: "9", 
    description: "-"},
    {category: "Jugo/Batido",
    imageUrl: "https://recetasdebatidos.com/wp-content/uploads/2021/02/batidos-de-frutas-naturales.jpg",
    name: "Limonada",
    price: "8", 
    description: "-"},
    {category: "Postre",
    imageUrl: "https://i.blogs.es/1c733d/postres/1366_2000.jpg",
    name: "Milk Shake",
    price: "12", 
    description: "Frapeado de frutas frutilla, piña y papaya"},
    {category: "Postre",
    imageUrl: "https://i.blogs.es/1c733d/postres/1366_2000.jpg",
    name: "Helado con Brownie.",
    price: "10", 
    description: "Porción de torta con helado"},
    {category: "Postre",
    imageUrl: "https://i.blogs.es/1c733d/postres/1366_2000.jpg",
    name: "Banana Split",
    price: "12", 
    description: "Helado acompañado de plátano"},
    {category: "Postre",
    imageUrl: "https://i.blogs.es/1c733d/postres/1366_2000.jpg",
    name: "Wafles con helado",
    price: "16", 
    description: "wafles acompañado con helado y fruta"},
    {category: "Cafe",
    imageUrl: "https://cafemaniacos.com.br/wp-content/uploads/2019/01/tipos-de-cafe.jpg",
    name: "Capuchino",
    price: "10", 
    description: "-"},
    {category: "Cafe",
    imageUrl: "https://cafemaniacos.com.br/wp-content/uploads/2019/01/tipos-de-cafe.jpg",
    name: "Mokaccino",
    price: "10", 
    description: "-"},
    {category: "Cafe",
    imageUrl: "https://cafemaniacos.com.br/wp-content/uploads/2019/01/tipos-de-cafe.jpg",
    name: "Expresso",
    price: "9", 
    description: "-"},
    {category: "Cafe",
    imageUrl: "https://cafemaniacos.com.br/wp-content/uploads/2019/01/tipos-de-cafe.jpg",
    name: "Cafe con leche",
    price: "8", 
    description: "-"},
    {category: "Cafe",
    imageUrl: "https://cafemaniacos.com.br/wp-content/uploads/2019/01/tipos-de-cafe.jpg",
    name: "Toddy con leche",
    price: "8", 
    description: "-"},
    {category: "Cafe",
    imageUrl: "https://cafemaniacos.com.br/wp-content/uploads/2019/01/tipos-de-cafe.jpg",
    name: "Toddy",
    price: "6", 
    description: "-"},
    {category: "Cafe",
    imageUrl: "https://cafemaniacos.com.br/wp-content/uploads/2019/01/tipos-de-cafe.jpg",
    name: "Destilado",
    price: "5", 
    description: "-"},
    {category: "Cafe",
    imageUrl: "https://cafemaniacos.com.br/wp-content/uploads/2019/01/tipos-de-cafe.jpg",
    name: "Te-Mate",
    price: "5", 
    description: "-"},
    {category: "Cafe",
    imageUrl: "https://cafemaniacos.com.br/wp-content/uploads/2019/01/tipos-de-cafe.jpg",
    name: "Sultana",
    price: "5", 
    description: "-"},
    {category: "Cafe",
    imageUrl: "https://cafemaniacos.com.br/wp-content/uploads/2019/01/tipos-de-cafe.jpg",
    name: "Copa melba",
    price: "10", 
    description: "-"},
    {category: "Cafe",
    imageUrl: "https://cafemaniacos.com.br/wp-content/uploads/2019/01/tipos-de-cafe.jpg",
    name: "Copa de chocolate y oreo",
    price: "10", 
    description: "-"},
    {category: "Cafe",
    imageUrl: "https://cafemaniacos.com.br/wp-content/uploads/2019/01/tipos-de-cafe.jpg",
    name: "Copa de frutilla y cherrys",
    price: "10", 
    description: "-"},
    {category: "Desayuno",
    imageUrl: "https://recetasdecocina.elmundo.es/wp-content/uploads/2022/08/desayuno-saludables-recetas.jpg",
    name: "Desayuno Paceño",
    price: "8", 
    description: "Pan marraqueta, queso y café"},
    {category: "Desayuno",
    imageUrl: "https://recetasdecocina.elmundo.es/wp-content/uploads/2022/08/desayuno-saludables-recetas.jpg",
    name: "Revuelto de huvos",
    price: "13", 
    description: "Acompañado de jamón, tomate, tostadas, café y jugo"},  
    {category: "Desayuno",
    imageUrl: "https://recetasdecocina.elmundo.es/wp-content/uploads/2022/08/desayuno-saludables-recetas.jpg",
    name: "Breake de huevos",
    price: "14", 
    description: "Omelette de verduras, tostadas, café y jugo"},
    {category: "Desayuno",
    imageUrl: "https://recetasdecocina.elmundo.es/wp-content/uploads/2022/08/desayuno-saludables-recetas.jpg",
    name: "Panqueques",
    price: "14", 
    description: "(4 unidades) Acompañado de frutas de estación, jarabe de chocolate, café o té"},
    {category: "Desayuno",
    imageUrl: "https://recetasdecocina.elmundo.es/wp-content/uploads/2022/08/desayuno-saludables-recetas.jpg",
    name: "Omelette de carne",
    price: "15", 
    description: "Omelette relleno de carne picada, tostadas y café"},
    {category: "Desayuno",
    imageUrl: "https://recetasdecocina.elmundo.es/wp-content/uploads/2022/08/desayuno-saludables-recetas.jpg",
    name: "Desayuno Ranchero",
    price: "15", 
    description: "Pan casero, salteado de carne con verduras, huevo frito, papas fritas, café o té"},
    {category: "Desayuno",
    imageUrl: "https://recetasdecocina.elmundo.es/wp-content/uploads/2022/08/desayuno-saludables-recetas.jpg",
    name: "Desayuno Continental",
    price: "15", 
    description: "Jamón, queso, tostadas, huevos, mermelada, mantequilla y café"},
    {category: "Desayuno",
    imageUrl: "https://recetasdecocina.elmundo.es/wp-content/uploads/2022/08/desayuno-saludables-recetas.jpg",
    name: "Waffles",
    price: "15", 
    description: "(3unidades) Acompañado de frutas de estación, jarabe de chocolate, café o té"},
    {category: "Desayuno",
    imageUrl: "https://recetasdecocina.elmundo.es/wp-content/uploads/2022/08/desayuno-saludables-recetas.jpg",
    name: "Desayuno Yungueño",
    price: "16", 
    description: "Lomito de res, huevo, tomate, arroz, plátano frito, pan casero, café o té"},
    {category: "Desayuno",
    imageUrl: "https://recetasdecocina.elmundo.es/wp-content/uploads/2022/08/desayuno-saludables-recetas.jpg",
    name: "ChocoWafles",
    price: "16", 
    description: "Wafles de chocolate con relleno de manjar, frutas de estación, café o té"},
    {category: "Desayuno",
    imageUrl: "https://recetasdecocina.elmundo.es/wp-content/uploads/2022/08/desayuno-saludables-recetas.jpg",
    name: "Desayuno Americano",
    price: "17", 
    description: "Tostadas, huevos revueltos, tocino, mermelada, mantequilla, café y jugo"},
    {category: "Sandwich",
    imageUrl: "https://i.blogs.es/1cbc97/collage_sanwich/1366_2000.jpg",
    name: "Sandwich de jamon y quso caliente",
    price: "6", 
    description: "Jamón y queso, pan miga"},
    {category: "Sandwich",
    imageUrl: "https://i.blogs.es/1cbc97/collage_sanwich/1366_2000.jpg",
    name: "Sandwich de jamon y quso frio",
    price: "7", 
    description: "Lechuga, tomate, aderezos y pan miga"},
    {category: "Sandwich",
    imageUrl: "https://i.blogs.es/1cbc97/collage_sanwich/1366_2000.jpg",
    name: "Sandwich croc madame",
    price: "10", 
    description: "3 capas de pan miga, jamón, queso mozarella y salsa bechamel"},
    {category: "Sandwich",
    imageUrl: "https://i.blogs.es/1cbc97/collage_sanwich/1366_2000.jpg",
    name: "Sandwich de lomito de res/huevo",
    price: "10", 
    description: "Pan, lechuga, tomate y aderezos"},
    {category: "Sandwich",
    imageUrl: "https://i.blogs.es/1cbc97/collage_sanwich/1366_2000.jpg",
    name: "Sandwich de lomito con queso/jamon",
    price: "10", 
    description: "Pan, lechuga, tomate y aderezos"},
    {category: "Sandwich",
    imageUrl: "https://i.blogs.es/1cbc97/collage_sanwich/1366_2000.jpg",
    name: "Sandwich de pollo a la plancha",
    price: "10", 
    description: "Pan, lechuga, tomate, cebolla en vinagre y aderezos"},
    {category: "Sandwich",
    imageUrl: "https://i.blogs.es/1cbc97/collage_sanwich/1366_2000.jpg",
    name: "Sandwich de pasta atún",
    price: "10", 
    description: "Pan blanco o integral, lechuga, pasta atún y tomate"},
    {category: "Sandwich",
    imageUrl: "https://i.blogs.es/1cbc97/collage_sanwich/1366_2000.jpg",
    name: "Tranca pecho",
    price: "12", 
    description: "Pan casero, arroz, apanado de res, huevo, pico de gallo y papas fritas"},
    {category: "Especial",
    imageUrl: "https://www.lamansiondelasideas.com/wp-content/uploads/2016/12/recetas-carne-fiestas.jpg",
    name: "Hamburquesa Clásica",
    price: "13", 
    description: "Pan, carne de res, lechuga, tomate, queso y papas fritas"},
    {category: "Especial",
    imageUrl: "https://www.lamansiondelasideas.com/wp-content/uploads/2016/12/recetas-carne-fiestas.jpg",
    name: "Minipique",
    price: "15", 
    description: "Salteado de carne, salchicha, cebolla, huevo duro, tomate y papas fritas"},
    {category: "Especial",
    imageUrl: "https://www.lamansiondelasideas.com/wp-content/uploads/2016/12/recetas-carne-fiestas.jpg",
    name: "Club sandwich",
    price: "17", 
    description: "3 capas de pan molde, filete de pollo, jamón, queso, tocino, tomate, lechuga y papas fritas"},
    {category: "Especial",
    imageUrl: "https://www.lamansiondelasideas.com/wp-content/uploads/2016/12/recetas-carne-fiestas.jpg",
    name: "Hamburguesa napolitana",
    price: "17", 
    description: "Pan, carne de res, jamón, queso, orégano, salsa de tomate, lechuga, tomate y papas fritas"},
    {category: "Especial",
    imageUrl: "https://www.lamansiondelasideas.com/wp-content/uploads/2016/12/recetas-carne-fiestas.jpg",
    name: "Hamburguesa BBQ",
    price: "18", 
    description: "Pan, carne de res, lechuga, tomate, pepinillos, salsa y papas fritas"},
    {category: "Especial",
    imageUrl: "https://www.lamansiondelasideas.com/wp-content/uploads/2016/12/recetas-carne-fiestas.jpg",
    name: "Hamburguesa criolla",
    price: "18", 
    description: "Pan, carne de res, queso criollo, huevo, chorrellana y papas fritas"},
    {category: "Especial",
    imageUrl: "https://www.lamansiondelasideas.com/wp-content/uploads/2016/12/recetas-carne-fiestas.jpg",
    name: "Porkyguesa",
    price: "20", 
    description: "Pan, carne de rest tomate, lechuga, salsa, crispis de cebolla, tocino y papas fritas"},
    {category: "Especial",
    imageUrl: "https://www.lamansiondelasideas.com/wp-content/uploads/2016/12/recetas-carne-fiestas.jpg",
    name: "Choriburguer",
    price: "20", 
    description: "Pan, carne de rest chorizo, lechuga, tomate, cebolla y salsa de ajo"},
    {category: "Especial",
    imageUrl: "https://www.lamansiondelasideas.com/wp-content/uploads/2016/12/recetas-carne-fiestas.jpg",
    name: "Tex Mex",
    price: "20", 
    description: "Pan, carne de res, palta, pico de gallo, nachos, queso mozarella y papas fritas"},
    {category: "Especial",
    imageUrl: "https://www.lamansiondelasideas.com/wp-content/uploads/2016/12/recetas-carne-fiestas.jpg",
    name: "Sandwich suizo",
    price: "22", 
    description: "Pan, lomo de res, crema de leche, champiñones, cebolla, salsa de soya, queso mozarella y papas fritas"},
    {category: "Especial",
    imageUrl: "https://www.lamansiondelasideas.com/wp-content/uploads/2016/12/recetas-carne-fiestas.jpg",
    name: "Pan pique",
    price: "15", 
    description: "Salteado de carne con cebolla, tomate, salchicha y papas fritas"},
    {category: "Ensalada",
    imageUrl: "https://i.blogs.es/b8b596/apertura-apaisada-ensaladas/1366_2000.jpg",
    name: "Ensalada Cesar",
    price: "15", 
    description: "Mix de lechugas, pollo a la plancha, croutons, queso parmesano, salsa de ajo y tomates"},
    {category: "Ensalada",
    imageUrl: "https://i.blogs.es/b8b596/apertura-apaisada-ensaladas/1366_2000.jpg",
    name: "Ensalada del valle",
    price: "15", 
    description: "Mix de lechugas, suprema de pollo, zanahoria, tomates, queso criollo, tostadas, salsa de ajo"},
    {category: "Ensalada",
    imageUrl: "https://i.blogs.es/b8b596/apertura-apaisada-ensaladas/1366_2000.jpg",
    name: "Ensalada verdulera",
    price: "17", 
    description: "Mix de lechugas, pollo a la plancha, palta, choclitos, jamón, tomates asados, zuchiny y salsa de albahaca"},
    {category: "Ensalada",
    imageUrl: "https://i.blogs.es/b8b596/apertura-apaisada-ensaladas/1366_2000.jpg",
    name: "Ensalada de atun",
    price: "16", 
    description: "Mix de lechugas, atún, huevo duro, rabanitos, queso criollo, tomates, maní tostado y choclitos"},
    {category: "Ensalada",
    imageUrl: "https://i.blogs.es/b8b596/apertura-apaisada-ensaladas/1366_2000.jpg",
    name: "Ensalada mexicana",
    price: "15", 
    description: "Mix de lechugas, palta, pico de gallo, choclitos, nachos, pollo a la plancha y aderezo de queso"},
    
]
export default menu
